language: java
jdk:
  - oraclejdk11
before_deploy:
  - cd build/macApp
  - zip -r SortVisualization.mac.zip SortVisualization.app
  - cd ../../build/launch4j
  - zip SortVisualization.win.zip SortVisualization.exe
  - cd ../..
deploy:
  provider: releases
  token: ${GITHUB_TOKEN}
  file_glob: true
  file:
    - build/libs/SortVisualization-*.jar
    - build/macApp/SortVisualization.mac.zip
    - build/launch4j/SortVisualization.win.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
