language: java
jdk:
  - oraclejdk11
deploy:
  provider: releases
  token: ${GITHUB_TOKEN}
  file_glob: true
  file: "build/libs/SortVisualization-*.jar"
  cleanup: false
  on:
    tags: true
    all_branches: true
