language: java
jdk:
  - oraclejdk7
deploy:
  provider: releases
  api-key: "8638657fcd2e4e9d3ad9e4173733d41b8e74d1c5"
  file-glob: true
  file:
    - "build/launch4j/SortVisualization.exe"
    - "build/macApp/SortVisualization.app"
    - "build/libs/SortVisualization-*.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
sudo: false
