language: java
jdk:
  - oraclejdk11
before_deploy:
  - zip build/libs/SortVisualization.win.zip build/launch4j/SortVisualization.exe
  - zip build/libs/SortVisualization.mac.zip build/macApp/SortVisualization.app
deploy:
  provider: releases
  token: ${GITHUB_TOKEN}
  file_glob: true
  file:
    - build/libs/SortVisualization-*.jar
    - build/libs/SortVisualization.mac.zip
    - build/libs/SortVisualization.win.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
